import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { FloatingNavbar } from "@/components/floating-navbar"
import Footer from "@/components/footer"
// Removed: import RippleEffect from "@/components/ui/ripple-effect"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  generator: "v0.dev",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <FloatingNavbar />
          {/* Removed: <RippleEffect /> */}
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
